config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :archives do
    member do
      get '/categories/edit', to: 'archives#edit_categories'
      patch :update_categories
      get '/categories/:category_slug', to: 'archives#show', as: :category
    end
  end
  resources :archive_documents do
    get :download, on: :member
  end

  get 'pages/about', as: 'about'

  root 'archives#index'
end

app/models/archive_document.rb
class ArchiveDocument < ApplicationRecord
  acts_as_taggable

  BULK_META = %i(id title body content_creator content_created_date
    content_created_time content_source donor is_secret_donor
    content_recipients media_type
    remote_content_url category_slug tag_list)

  extend Enumerize
  enumerize :media_type, in: %i[문서 사진 도면 영상 음성]

  before_save :update_content_attributes

  belongs_to :user
  belongs_to :archive
  belongs_to :category, class_name: 'ArchiveCategory', optional: true, primary_key: :slug, foreign_key: :category_slug
  has_one :clypit, dependent: :destroy
  has_one :sewol_inv_document, dependent: :nullify, class_name: 'Archive::SewolInvDocument'

  attr_accessor :google_access_token

  has_one_attached :content

  validates :title, presence: true
  validates :body, presence: true
  validates :category_slug, presence: true

  default_scope { order('content_created_date DESC, content_created_time DESC, created_at DESC, id DESC') }
  scope :recent, -> { order('id DESC') }
  scoped_search on: [:title]

  def original_filename_attribute
    :content_name
  end

  def has_content?
    read_attribute(:content).present?
  end

  def image?
    content_type.try(:start_with?, 'image')
  end

  def valid_name
    return false if content_name.blank?
    self.content_name.gsub(/\\+/, "%20")
  end

  def parse_content_created_date
    return [nil, nil, nil] if content_created_date.blank?

    year = content_created_date[0..3]
    month = content_created_date[4..5]
    day = content_created_date[6..7]

    [year, (month if month != "00"), (day if day != "00")]
  end

  # bulk

  def self.bulk_attributes
    BULK_META
  end

  def self.bulk_human_attribute_names
    BULK_META.map { |a| human_attribute_name(a) }
  end

  def self.bulk_human_attribute_helps
    BULK_META.map { |a| I18n.t("messages.xlsx_help.archive_document.#{a}", default: "") }
  end

  def self.bulk_attribute_index(attribute)
    BULK_META.index(attribute.to_sym)
  end

  def before_process_bulk(bulk_task)
    self.archive = bulk_task.archive
    self.google_access_token = bulk_task.google_access_token
    self.user = bulk_task.user
  end

  def process_bulk_of_is_secret_donor(value)
    if value == "예"
      self.is_secret_donor = true
    else
      self.is_secret_donor = false
    end
  end

  def process_bulk_of_remote_content_url(value)
    return if value.blank?

    begin
      google_file = google_drive_session.file_by_url(value)
    rescue GoogleDrive::Error
      self.remote_content_url = value
      return
    end

    Tempfile.open(['archive', File.extname(google_file.title)]) do |temp_file|
      google_file.download_to_file(temp_file.path)

      self.content = temp_file.open
      self.content_name = google_file.title
    end
  end

  def human_formatted_content_created_datetime
    year, month, day = parse_content_created_date
    "#{[year.try('+', '.'), month.try('+', '.'), day.try('+', '.')].compact.join('')} #{content_created_time}".try(:strip)
  end

  def human_formatted_donor
    "#{is_secret_donor ? '비공개' : donor}"
  end

  private

  def update_content_attributes
    if read_attribute(:content).present? && content_changed?
      self.content_type = content.file.content_type
      self.content_size = content.file.size
    end
  end
end

app/controllers/archive_documents_controller.rb
class ArchiveDocumentsController < ApplicationController
  load_and_authorize_resource

  def show
    @archive = @archive_document.archive
    @documents = params[:tag].present? ? @archive.documents.tagged_with(params[:tag]) : @archive.documents
    @documents = @documents.page(params[:page])
  end

  def new
    @archive ||= Archive.find(params[:archive_id])
    @archive_document.archive = @archive
  end

  def create
    @archive_document.user = current_user
    if @archive_document.save
      redirect_to archive_path(@archive_document.archive)
    else
      errors_to_flash_now(@archive_document)
      @archive = @archive_document.archive
      render :new
    end
  end

  def edit
    @archive = @archive_document.archive
  end

  def update
    if @archive_document.update(archive_document_params)
      redirect_to @archive_document
    else
      errors_to_flash_now(@archive_document)
      render :edit
    end
  end

  def destroy
    @archive_document.destroy
    redirect_to archive_path(@archive_document.archive)
  end

  def download
    send_data @archive_document.content.download, filename: @archive_document.content.filename, content_type: @archive_document.content.content_type, disposition: 'attachment', stream: 'true', buffer_size: '4096'
  end

  private

  def archive_document_params
    params.require(:archive_document).permit(
      :archive_id,
      :title, :body, :tag_list,
      :content_creator, :content_created_date, :content_created_time,
      :content_source, :content_recipients,
      :content, :media_type, :remove_content,
      :category_slug, :donor, :is_secret_donor
    )
  end
end

app/views/archive_documents/_form.html.haml
= form_for @archive_document do |f|
  = f.hidden_field :archive_id

  .form-group
    = f.label :title
    = f.text_field :title, required: true, class: 'form-control'

  .form-group
    = f.label :body
    ~ f.text_area :body, class: 'form-control redactor'

  - if params[:category_slug].present?
    = f.hidden_field :category_slug, value: params[:category_slug]
  - else
    - if @archive_document.archive.categories.any?
      .form-group
        = f.label :category_slug
        = f.select :category_slug, [], {}, {class: 'form-control'} do
          - @archive_document.archive.categories.each do |category|
            %optgroup{ label: category.name }
            - category.children.each do |subcategory|
              %option{ value: subcategory.slug, selected: subcategory.slug == f.object.category_slug }
                = subcategory.slug
                \-
                = subcategory.name
    - else
      = f.hidden_field :category_slug

  .form-group
    = f.label :tag_list
    = f.text_field :tag_list, value: @archive_document.tag_list.try(:to_s), placeholder: '태그1, 태그2, 태그3', class: 'form-control'
    %p.help-block
      콤마로 태그를 구분해서 넣으세요.

  %hr

  .form-group
    = f.label :content
    = f.file_field :content, class: 'form-control'
    .help-block
    - if @archive_document.read_attribute(:content).present?
      - if @archive_document.image?
        = image_tag @archive_document.content.xs.url, class: 'img-thumbnail', style: 'max-width: 40px'
      - else
        = @archive_document.content_name
      %label{ style: 'font-weight: normal;' }
        = f.check_box :remove_content
        삭제하기

  .form-group
    = f.label :media_type
    = f.select :media_type, ArchiveDocument.media_type.options, {}, class: 'form-control'

  .form-group
    = f.label :content_creator
    = f.text_field :content_creator, class: 'form-control'

  .form-group
    = f.label :content_source
    = f.text_field :content_source, class: 'form-control'

  .form-group
    = f.label :content_recipients
    = f.text_field :content_recipients, class: 'form-control'

  .form-group
    = f.label :donor
    = f.text_field :donor, class: 'form-control'
    .help-block
      %label{ style: 'font-weight: normal;' }
        = f.check_box :is_secret_donor
        숨깁니다

  .row
    .col-sm-6
      .form-group
        = f.label :content_created_date
        = f.text_field :content_created_date, class: 'form-control'
      .help-block
        %p 기록물의 생산년도, 월, 일 을 구분기호없이 8자리 입력(예:20160330) 생산년도만 알고 월/일을 모르는 경우 '20160000'으로, 일자를 모르는 경우 '20160300'으로 처리함

    .col-sm-6
      .form-group
        = f.label :content_created_time
        = f.text_field :content_created_time, placeholder: 'hh:mm:ss', class: 'form-control'

  .form-group
    = f.submit '저장', class: 'btn btn-primary'
    = link_to '취소', :back, class: 'btn btn-default'

app/views/archive_documents/_list.html.haml
%section#archive-category.page-block
  .container
    .row
      .hidden-xs.col-sm-3
        .ui.vertical.menu
          - @archive.categories.each do |category|
            .item{ class: ('active' if category == @category.try(:parent)) }
              .header= category.name
              .menu
                - category.children.each do |subcategory|
                  .item{ class: ('active' if subcategory == @category) }
                    = link_to subcategory.name, category_archive_path(@archive, category_slug: subcategory.slug)

      .col-sm-9.col-xs-12
        - if @category.try(:desc).present?
          .sub.header= @category.desc
        - if @documents.empty?
          .ui.message
            %p 해당 자료가 없습니다.
        - else
          .ui.divided.items
            - @documents.each do |document|
              .item
                - if document.image?
                  .image
                    = image_tag document.content.sm.url
                .content
                  .header
                    = file_type_icon(document.content_type)
                    = link_to document.title, archive_document_path(document)
                  .meta
                    - if document.content_created_date.present?
                      %span
                        생성일:
                        = document.content_created_date
                        = document.content_created_time
                  .description
                    %p= strip_tags document.body
                  - if document.tags.any?
                    .extra
                      - document.tags.each do |tag|
                        .ui.label= tag

        .text-center
          = paginate @documents

        - if can? :manage, @archive
          = link_to '자료입력', new_archive_document_path(archive_id: @archive.id, category_slug: params[:category_slug]), class: 'ui primary button'

app/views/archive_documents/edit.html.haml
%section.page-block
  .container
    .page-header
      %h2 수정
    = render 'form'

app/views/archive_documents/new.html.haml
%section.page-block
  .container
    .page-header
      %h3
        %strong= @archive.title
        자료 추가
        - if params[:category_slug].present? and @archive.category_by_slug(params[:category_slug]).present?
          \- #{@archive.category_by_slug(params[:category_slug]).name} 카테고리
    = render 'form'

app/views/archive_documents/show.html.haml
%section#archive_document-block.page-block.post-block
  .container
    .post-block__title
      %h4
        = @archive_document.title

    .post-block__info
      %span.post-block__date
        = human_datetime_f @archive_document.created_at
      - if can? :edit, @archive_document
        = link_to '수정', edit_archive_document_path(@archive_document)
      - if can? :destroy, @archive_document
        = link_to '삭제', @archive_document, method: :delete, data: { confirm: '삭제하시겠습니까?' }

    .post-block__content
      - if @archive_document.has_content?
        .panel.panel-default
          .panel-heading
            .download
              = link_to [:download, @archive_document] do
                = file_type_icon(@archive_document.content_type)
                #{@archive_document.content_name}
                %i.fa.fa-download
            - if @archive_document.clypit.present?
              .clypit
                %iframe{ frameborder: "0", height: "160", src: "https://clyp.it/#{@archive_document.clypit.audio_file_id}/widget", width: "100%"}

          - if @archive_document.image?
            .panel-body
              .image
                = image_tag @archive_document.content.md.url

    .post-block__body
      = raw @archive_document.body
      - if @archive_document.sewol_inv_document.present?
        %p
          %i.fa.fa-info-circle
          %a(href='http://www.archives.go.kr/' target='_blank')> 국가기록원
          에 보관 중인 자료입니다.

    .panel.panel-default
      .panel-heading
        - if @archive_document.sewol_inv_document.present?
          - sewol_inv_document = @archive_document.sewol_inv_document
          - %i(code reporter reviewer open_type open_level_desc open_retype).each do |attribute|
            - if sewol_inv_document.send(attribute).present?
              %div
                #{Archive::SewolInvDocument.human_attribute_name(attribute)}: #{sewol_inv_document.send(attribute)}
        - else
          - %i(content_source content_creator human_formatted_content_created_datetime content_recipients human_formatted_donor).each do |attribute|
            - if @archive_document.send(attribute).present?
              %div
                #{ArchiveDocument.human_attribute_name(attribute)}: #{@archive_document.send(attribute)}
        %div
          등록일: #{l @archive_document.created_at}