config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :archives do
    member do
      get '/categories/edit', to: 'archives#edit_categories'
      patch :update_categories
      get '/categories/:category_slug', to: 'archives#show', as: :category
    end
  end
  resources :archive_documents do
    get :download, on: :member
  end

  get 'pages/about', as: 'about'

  root 'archives#index'
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :user
  has_many :documents, class_name: 'ArchiveDocument', dependent: :destroy
  has_many :all_categories, class_name: 'ArchiveCategory', dependent: :destroy
  has_many :categories, -> { where parent: nil }, class_name: 'ArchiveCategory'
  has_many :subcategories, -> { where.not parent: nil }, class_name: 'ArchiveCategory'
  has_many :bulk_tasks, dependent: :destroy

  accepts_nested_attributes_for :categories, allow_destroy: true

  # mount_uploader :cover_image, ImageUploader
  # mount_uploader :social_image, ImageUploader

  has_one_attached :cover_image
  has_one_attached :sns_image

  validates :title, presence: true
  validates :body, presence: true
  validates :cover_image, presence: true

  default_scope { order('updated_at DESC') }

  # def contributors
  #   (documents.collect{|d| d.user} + [user]).uniq
  # end

  def category_by_slug(slug)
    all_categories.find_by(slug: slug)
  end
end

app/models/archive/sewol_inv_document.rb
class Archive::SewolInvDocument < ApplicationRecord
  belongs_to :archive_document
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  load_and_authorize_resource

  def index
    @archives = Archive.page(params[:page])
  end

  def show
    @category = @archive.all_categories.find_by(slug: params[:category_slug])
    @documents = @archive.documents
    @documents = @documents.tagged_with(params[:tag]) if params[:tag].present?
    @documents = @documents.where(category_slug: params[:category_slug]) if params[:category_slug].present?
    @documents = @documents.page(params[:page])

    if params[:q].present?
      @documents = @documents.search_for params[:q]
    end
  end

  def new
    @archive = Archive.new
  end

  def create
    @archive = Archive.new(archive_params)
    @archive.user = current_user

    if @archive.save
      redirect_to @archive
    else
      errors_to_flash_now(@archive)
      render "new"
    end
  end

  def edit
  end

  def update
    if @archive.update(archive_params)
      redirect_to @archive
    else
      errors_to_flash_now(@archive)
      render "edit"
    end
  end

  def update_categories
    if @archive.update(archive_params)
      redirect_to @archive
    else
      errors_to_flash_now(@archive)
      render 'edit_categories'
    end
  end

  def destroy
    @archive.destroy
    redirect_to archives_path
  end

  private

  def archive_params
    params.require(:archive).permit(
      :title, :body, :cover_image, :sns_image, :slug,
      categories_attributes: [ :id, :slug, :name, :desc, :_destroy, children_attributes: [ :archive_id, :id, :slug, :name, :desc, :_destroy ] ]
    )
  end
end

app/views/archives/_archive.html.haml
.mb-4.card
  -# = image_tag archive.cover_image, class: "card-img-top"
  .card-body
    %h5.card-title= link_to archive.title, archive

    %p.card-text
      %small= strip_tags(archive.body).truncate(150)
      %br
      %small
        #{archive.documents.count}개의 자료
  .card-footer
    %small.text-muted
      %i.far.fa-clock
      = l archive.updated_at

app/views/archives/_form.html.haml
= simple_form_for @archive do |f|
  = f.input :title
  = f.input :body, input_html: { rows: 10 }

  .form-group
    = f.label :slug
    = f.text_field :slug, class: 'form-control'
  .form-group
    = f.label :cover_image
    = f.file_field :cover_image, class: 'form-control'
    .help-block
    - if @archive.cover_image.attached?
      = image_tag @archive.cover_image.variant(resize: "300x200"), class: 'img-thumbnail', style: 'max-width: 40px'
  .form-group
    = f.label :sns_image
    = f.file_field :sns_image, class: 'form-control'
    .help-block
    - if @archive.sns_image.attached?
      = image_tag @archive.sns_image.variant(resize: "300x200"), class: 'img-thumbnail', style: 'max-width: 40px'
  = f.submit data: { disable_with: "Please wait..." }, class: 'btn btn-primary'

app/views/archives/edit.html.haml
%h2.pb-2 데이터 셋 보완하기

= render 'form'

app/views/archives/edit_categories.html.haml
= render 'archive_categories/list', archive: @archive

app/views/archives/index.html.haml
%h2.pb-2
  = t('title.main')

.row
  - @archives.each do |archive|
    .col-6
      = render archive

.d-flex.justify-content-center
  = paginate @archives

app/views/archives/new.html.haml
%h2.pb-2 데이터 셋 추가하기

= render 'form'

app/views/archives/show.html.haml
%h2.pb-2= @archive.title

.my-4.p-3.border.bg-white
  = raw @archive.body

.my-4
  .d-flex.justify-content-between
    %div
      - if user_signed_in?
        = link_to t('link.edit'), edit_archive_path(@archive), class: "btn btn-outline-primary"
    %div
      - if user_signed_in? && (@archive.user == current_user || current_user.admin?)
        = link_to t('link.destroy'), @archive, method: :delete, data: { confirm: "정말 삭제하시겠습니까?" }, class: "btn btn-outline-danger"
    %div
      - if can? :edit, @archive
        = link_to '분류관리', categories_edit_archive_path(@archive), class: "btn btn-outline-info"
  %hr

  = render 'archive_documents/list', archive: @archive

%hr

.my-4
  %h5.text-muted= Archive.human_attribute_name("comments")
  .my-4.p-4.border.bg-white
    = link_to "아카이브에 관한 의견이 있으세요?", "https://democracy-activists.parti.xyz/p/data_activists", target: "_blank", class: "text-dark"