config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :archives do
    member do
      get '/categories/edit', to: 'archives#edit_categories'
      patch :update_categories
      get '/categories/:category_slug', to: 'archives#show', as: :category
    end
  end
  resources :archive_documents do
    get :download, on: :member
  end

  get 'pages/about', as: 'about'

  root 'archives#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def errors_to_flash(model)
    flash[:error] = model.errors.full_messages.join('<br>').html_safe
  end

  def errors_to_flash_now(model)
    flash.now[:error] = model.errors.full_messages.join('<br>').html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALLOWED_EXTENSIONS = %w(txt doc docx xls xlsx ppt pptx bmp gif jpeg jpg png bz2 dmg gz gzip iso rar tar tgz zip)
  def file_type_icon(content_type)
    mime_type = MIME::Types[content_type].first
    extension = mime_type.try(:preferred_extension)
    extension = 'txt' unless ALLOWED_EXTENSIONS.include?(extension)
    content_tag(:i, nil, class: ["fa", "fa-file-#{extension}-o"])
  end

  def human_datetime_f(date)
    date.strftime("%Y년 %m월 %d일 %H:%M")
  rescue ArgumentError
    date
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages()
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/views/application/_aside.html.haml
= render "search_bar"

%section
  .mb-4
    .bg-white.border.p-3
      .media
        = image_tag 'parti_symbol.png', width: 70, class: "mr-3"
        .media-body
          %h5.mt-0= link_to '빠띠 데이터 활동가 커뮤니티', "https://democracy-activists.parti.xyz/p/data_activists", target: "_blank", class: "text-dark"
          = link_to "데이터로 더 투명하고 신뢰하는 사회를 만듭니다", "https://democracy-activists.parti.xyz/p/data_activists", target: "_blank", class: "text-dark"

app/views/application/_header.html.haml
%header
  %nav.navbar.fixed-top.navbar-dark.justify-content-start{ style: "background-color:#000" }
    %button.navbar-toggler.p-0.border-0.mr-2{"data-toggle" => "offcanvas", :type => "button"}
      %span.navbar-toggler-icon

    .navbar-collapse.offcanvas-collapse{ style: "background-color:#000" }
      %ul.navbar-nav

        %li.nav-item.mt-4
          %small.text-light
            %i.far.fa-database
          = link_to t("menu.archives"), archives_path, class: "p-2 nav-link"
        - if user_signed_in?
          %li.nav-item
            = link_to t("link.new_archive"), new_archive_path, class: "btn btn-primary btn-sm"

        %li.nav-item.mt-4
          %small.text-light
            %i.far.fa-user
        - if user_signed_in?
          %li.nav-item
            .nav-link
              #{current_user.name} (#{current_user.email})
          %li.nav-item= link_to t("link.sign_out"), destroy_user_session_path, method: :delete, class: "nav-link"
        - else
          %li.nav-item= link_to t("link.sign_in"), new_user_session_path, class: "nav-link"

    .mr-auto
      = link_to t("site_name"), root_path, class: "navbar-brand"

    = form_with url: archives_path, method: :get, local: true, class: "form-inline" do |f|
      = f.text_field :q, value: params[:q], placeholder: "검색", class: "form-control form-control-sm"